stages:
  - test
  - dockerize
  - deploy_test
  - deploy

image: python:3.9-slim-bookworm

variables:
  IMAGE_NAME: "eshkt/yaml-docker-hub"
  IMAGE_TAG: "first-container"
  APP_NAME: "yaml-docker-hub"

run_test:
  before_script:
    - apt-get update && apt-get install -y make
  stage: test
  script:
    - make test
build_image:
  stage: dockerize
  image: docker:27.5.1
  services:
    - docker:27.5.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - echo "Buidling docker for $DOCKER_USER"
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  script:
    - echo "Docker User is $DOCKER_USER"
    - echo "EC2 Host is $EC2_HOST"
  only:
    - main

test_deploy:
  stage: deploy_test
  script:
  - echo "Checking visibility..."
    - if [ -z "$SSH_PRIVATE_KEY" ]; then echo "KEY is MISSING"; else echo "KEY is FOUND"; fi
    - if [ -z "$EC2_HOST" ]; then echo "HOST is MISSING"; else echo "HOST is FOUND"; fi
    - echo "The value of HOST is [${EC2_HOST}]"


deploy_to_ec2:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    # --- DEBUG SECTION ---
    - echo "Checking variables..."
    - if [ -z "$EC2_HOST" ]; then echo "ERROR - EC2_HOST is empty in GitLab Settings"; exit 1; fi
    #-------------
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
  script:
    - |
      ssh $EC2_USER@$EC2_HOST"

      #this is to install docker 
      if ! command -v docker &> /dev/null; then
          echo "Docker not found, now installing..."
          sudo dnf update -y
          sudo dnf install -y docker 
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo user mod -a -G docker $EC2_USER
          echo "Docker installed successfully."
        fi 

        #2 Re-login to apply docker group permissions 
        sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
        sudo docker pull $IMAGE_NAME:$IMAGE_TAG
        sudo docker stop $APP_NAME || true
        sudo docker rm $APP_NAME || true
        sudo docker run -d --name $APP_NAME -p 80:5000 -p 443:5000 $IMAGE_NAME:$IMAGE_TAG
        "