stages:
  - test
  - dockerize
  - deploy

image: python:3.9-slim-bookworm

variables:
  IMAGE_NAME: "eshkt/yaml-docker-hub"
  IMAGE_TAG: "first-container"
  APP_NAME: "yaml-docker-hub"
  EC2_USER: "ec2-user"

run_test:
  before_script:
    - apt-get update && apt-get install -y make
  stage: test
  script:
    - make test
build_image:
  stage: dockerize
  image: docker:27.5.1
  services:
    - docker:27.5.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main

deploy_to_ec2:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
  script:
    -ssh $EC2